import { NextResponse } from 'next/server';

const TEMPLATES = [
  { id: 'cold_outreach', name: 'Cold Outreach to Recruiter', category: 'Networking', subject: 'Experienced {role} — interested in opportunities at {company}', body: 'Hi {recruiter_name},\n\nI came across {company} and was impressed by {specific_reason}. As a {role} with {years} years of experience in {skills}, I believe I could contribute meaningfully to your team.\n\nI\'d love the chance to chat about any open roles. Would you be available for a brief call this week?\n\nBest regards,\n{your_name}' },
  { id: 'referral_request', name: 'Referral Request', category: 'Networking', subject: 'Would you be open to referring me at {company}?', body: 'Hi {contact_name},\n\nI hope you\'re doing well! I noticed {company} has an opening for {role} that aligns perfectly with my background.\n\nGiven your experience there, would you be comfortable submitting a referral for me? I\'d be happy to send over my resume and a brief summary of why I\'m a strong fit.\n\nThank you so much for considering!\n\nBest,\n{your_name}' },
  { id: 'thank_you_interview', name: 'Thank You After Interview', category: 'Post-Interview', subject: 'Thank you for the interview — {role} position', body: 'Dear {interviewer_name},\n\nThank you for taking the time to speak with me today about the {role} position. I really enjoyed learning more about {specific_topic_discussed}.\n\nOur conversation reinforced my enthusiasm for the role. I\'m particularly excited about {specific_aspect}.\n\nPlease don\'t hesitate to reach out if you need any additional information.\n\nBest regards,\n{your_name}' },
  { id: 'follow_up_application', name: 'Follow Up on Application', category: 'Follow-Up', subject: 'Following up — {role} application', body: 'Dear Hiring Manager,\n\nI submitted my application for the {role} position on {date} and wanted to follow up to express my continued interest.\n\nWith my background in {skills}, I\'m confident I can add value to your team. I\'d welcome the opportunity to discuss how my experience aligns with your needs.\n\nThank you for your consideration.\n\nBest regards,\n{your_name}' },
  { id: 'no_response', name: 'No Response Follow Up', category: 'Follow-Up', subject: 'Checking in — {role} interview', body: 'Hi {contact_name},\n\nI hope this message finds you well. I wanted to follow up on our interview on {date} for the {role} position.\n\nI remain very interested in the opportunity and would love to hear about next steps when you have a moment.\n\nThank you for your time.\n\nBest,\n{your_name}' },
  { id: 'rejection_response', name: 'Response to Rejection', category: 'Post-Decision', subject: 'Re: {role} position', body: 'Dear {contact_name},\n\nThank you for letting me know about the decision. While I\'m disappointed, I truly appreciate the time and consideration throughout the process.\n\nI was impressed by {company} and would welcome the opportunity to be considered for future roles that align with my skills.\n\nWishing you and the team continued success.\n\nBest regards,\n{your_name}' },
  { id: 'accept_offer', name: 'Accept Job Offer', category: 'Post-Decision', subject: 'Offer acceptance — {role}', body: 'Dear {contact_name},\n\nI\'m thrilled to formally accept the offer for the {role} position at {company}. Thank you for this incredible opportunity.\n\nI\'m excited to join the team and contribute to {specific_goal}. I confirm my start date of {start_date} and look forward to completing any remaining onboarding steps.\n\nPlease let me know if there\'s anything I should prepare before my first day.\n\nBest regards,\n{your_name}' },
  { id: 'decline_offer', name: 'Decline Job Offer', category: 'Post-Decision', subject: 'Re: {role} offer at {company}', body: 'Dear {contact_name},\n\nThank you so much for offering me the {role} position at {company}. After careful consideration, I\'ve decided to pursue a different opportunity that more closely aligns with my current career goals.\n\nThis was not an easy decision — I was genuinely impressed by the team and the work being done at {company}.\n\nI hope we can stay connected and perhaps work together in the future.\n\nBest regards,\n{your_name}' },
  { id: 'networking_intro', name: 'Networking Introduction', category: 'Networking', subject: 'Fellow {industry} professional — would love to connect', body: 'Hi {contact_name},\n\nI\'m {your_name}, a {role} based in {location}. I came across your profile and was really interested in your work on {specific_topic}.\n\nI\'m currently exploring opportunities in {area} and would love to learn from your experience. Would you be open to a brief 15-minute chat?\n\nThanks for considering!\n\nBest,\n{your_name}' },
  { id: 'informational_interview', name: 'Informational Interview Request', category: 'Networking', subject: 'Seeking career advice — {industry}', body: 'Dear {contact_name},\n\nI admire your career path in {industry} and would greatly value your perspective as I navigate my own career transition.\n\nWould you be open to a 20-minute informational interview? I\'m particularly curious about {specific_question}.\n\nI\'m happy to work around your schedule. Thank you for considering.\n\nBest regards,\n{your_name}' },
];

export async function GET() {
  const categories = [...new Set(TEMPLATES.map(t => t.category))];
  return NextResponse.json({ templates: TEMPLATES, categories });
}
