import Link from 'next/link';
import { Zap } from 'lucide-react';

export const metadata = { title: 'Terms of Service' };

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white dark:bg-slate-950">
      <nav className="border-b bg-white/80 dark:bg-slate-950/80 backdrop-blur-sm sticky top-0 z-50">
        <div className="max-w-3xl mx-auto px-4 h-16 flex items-center">
          <Link href="/" className="flex items-center gap-2">
            <Zap className="h-6 w-6 text-blue-600" />
            <span className="text-lg font-bold">AutoApply AI</span>
          </Link>
        </div>
      </nav>

      <main className="max-w-3xl mx-auto px-4 py-12">
        <h1 className="text-3xl font-bold mb-8">Terms of Service</h1>

        <div className="prose dark:prose-invert max-w-none space-y-6 text-sm text-slate-600 dark:text-slate-400">
          <p><strong>Last updated:</strong> April 2026</p>

          <h2 className="text-lg font-semibold text-slate-900 dark:text-white">1. Acceptance of Terms</h2>
          <p>By accessing and using AutoApply AI, you agree to be bound by these Terms of Service. If you do not agree, please do not use the service.</p>

          <h2 className="text-lg font-semibold text-slate-900 dark:text-white">2. Description of Service</h2>
          <p>AutoApply AI provides AI-powered job application tools including resume generation, cover letter creation, job tracking, and automated application submission for job platforms.</p>

          <h2 className="text-lg font-semibold text-slate-900 dark:text-white">3. User Accounts</h2>
          <p>You are responsible for maintaining the confidentiality of your account credentials. You must provide accurate information during registration.</p>

          <h2 className="text-lg font-semibold text-slate-900 dark:text-white">4. Acceptable Use</h2>
          <p>You agree not to misuse the service, including but not limited to: submitting fraudulent applications, using the service for spam, or violating any applicable laws.</p>

          <h2 className="text-lg font-semibold text-slate-900 dark:text-white">5. AI-Generated Content</h2>
          <p>Content generated by our AI (resumes, cover letters) is provided as a starting point. You are responsible for reviewing and editing all content before use.</p>

          <h2 className="text-lg font-semibold text-slate-900 dark:text-white">6. Subscription and Payments</h2>
          <p>Paid plans are billed monthly. You may cancel at any time. Refunds are handled on a case-by-case basis.</p>

          <h2 className="text-lg font-semibold text-slate-900 dark:text-white">7. Limitation of Liability</h2>
          <p>AutoApply AI is provided &quot;as is&quot; without warranties. We are not liable for any damages arising from your use of the service, including but not limited to failed job applications.</p>

          <h2 className="text-lg font-semibold text-slate-900 dark:text-white">8. Changes to Terms</h2>
          <p>We reserve the right to modify these terms at any time. Continued use of the service constitutes acceptance of updated terms.</p>

          <h2 className="text-lg font-semibold text-slate-900 dark:text-white">9. Contact</h2>
          <p>For questions about these terms, contact us at support@autoapply.ai</p>
        </div>
      </main>
    </div>
  );
}
